// ThalCapacityCalibration.java
// Document Version 1.0.0
// Creation date: 2026/07/15
// Creator: Thalassicus

package thalassicus.archive;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//
// ============================================================================
// THAL CAPACITY CALIBRATION
// ============================================================================
// Loads per-NEED calibration factors from a data file (thal-capacity-
// calibration.json, deployed alongside thal-visit-duration-final.json),
// each correcting the Special Case formula for everything it does not and
// cannot model (non-Subject population composition, non-zero travel time,
// imperfect distribution, etc.) - see the project plan doc for the full
// derivation (observed/predicted occupancy, via Little's Law, averaged over
// a savefile's lifetime via ThalWelfordMean).
//
// getFactor(needKey) returns 1.0 for any NEED with no entry, and for every
// NEED if the file is missing or unreadable entirely - this is a
// deliberate design choice, not just a safe default: a factor of 1.0 makes
// the calibrated formula mathematically identical to the original,
// uncalibrated one, so a missing/deleted/not-yet-generated calibration
// file degrades gracefully to exactly today's shipped behavior rather than
// requiring a separate fallback code path. This resolves what would
// otherwise be a chicken-and-egg problem: the calibration file is itself
// generated by this same mod, so there must always be a sane behavior for
// the state before one has ever been produced.
//
// A missing file is logged at INFO, not WARN: unlike
// ThalServiceVisitDurations (where a missing file after the mod has been in
// use for a while would be surprising), a missing calibration file is the
// completely expected, normal starting state - nothing has gone wrong.
//
// Parsing uses the same minimal, purpose-built regex approach as
// ThalServiceVisitDurations, for the same reason documented there: this is
// our own generated file, not one of Jake's own data files, so a small
// parser tailored to a known flat structure is simpler and more robust than
// pulling in Jake's own idiosyncratic Json class. The regex only harvests
// ALL-CAPS "KEY": number pairs (matching the established convention that
// every NEED key is all-uppercase, optionally underscore-prefixed), so it
// naturally ignores whatever other structural or metadata fields (a "note"
// string, population/species breakdowns, etc.) the eventual calibration-
// file generator ends up including alongside the factors themselves.
// ============================================================================
//

public final class DEPRECATEDThalCapacityCalibration {

  private static final String DATA_FILE_PATH =
      System.getenv("APPDATA") + "\\songsofsyx\\mods\\Service Estimate Fix\\V71\\thal-capacity-calibration.json";

  private static final Pattern FACTOR_ENTRY_PATTERN =
      Pattern.compile("\"([A-Z_][A-Z0-9_]*)\"\\s*:\\s*([0-9.eE+-]+)");

  private static Map<String, Double> factorsByNeedKey;
  private static boolean dataFileLoaded;

  private DEPRECATEDThalCapacityCalibration() {
  }

  public static double getFactor(String needKey) {
    ensureLoaded();
    Double factor = factorsByNeedKey.get(needKey);
    return factor == null ? 1.0 : factor;
  }

  public static boolean dataFileLoaded() {
    ensureLoaded();
    return dataFileLoaded;
  }

  private static void ensureLoaded() {
    if (factorsByNeedKey != null) {
      return;
    }

    factorsByNeedKey = new HashMap<>();
    dataFileLoaded = false;

    String fileContents;
    try {
      fileContents = Files.readString(Path.of(DATA_FILE_PATH));
    } catch (IOException readFailure) {
      DEPRECATEDThalAIScanner.log.info(
          "No capacity-calibration file found at %s (%s); using an uncalibrated factor of 1.0 for every NEED.",
          DATA_FILE_PATH, readFailure.getMessage());
      return;
    }

    try {
      Matcher matcher = FACTOR_ENTRY_PATTERN.matcher(fileContents);
      while (matcher.find()) {
        String needKey = matcher.group(1);
        double factor = Double.parseDouble(matcher.group(2));
        factorsByNeedKey.put(needKey, factor);
      }
    } catch (NumberFormatException parseFailure) {
      DEPRECATEDThalAIScanner.log.warn(
          "Capacity-calibration file at %s contained an unparseable number (%s); using an uncalibrated factor of 1.0 for every NEED.",
          DATA_FILE_PATH, parseFailure.getMessage());
      factorsByNeedKey.clear();
      return;
    }

    dataFileLoaded = !factorsByNeedKey.isEmpty();
    if (dataFileLoaded) {
      DEPRECATEDThalAIScanner.log.info("Loaded %d capacity-calibration factor(s) from %s.", factorsByNeedKey.size(), DATA_FILE_PATH);
    } else {
      DEPRECATEDThalAIScanner.log.warn(
          "Capacity-calibration file at %s parsed without error but contained no usable factors; using an uncalibrated factor of 1.0 for every NEED.",
          DATA_FILE_PATH);
    }
  }
}
