# process_visit_durations.py
# Document Version 1.0.1
# Creation date: 2026/07/13
# Creator: Thalassicus
#
# Reads the raw per-room visit-duration bundle (visit-duration-source-data.json,
# hand-assembled from the decompiled AI plan classes) and produces a small,
# final data file mapping each analyzed room to a single visit-duration figure,
# picked according to that room's recorded strategy (measured_average / minimum
# / maximum), expressed both in raw seconds and as a ratio against a reference
# room. The reference room is Lavatory, since its estimate has already been
# checked against real gameplay.
#
# This script is meant to be re-run whenever the source bundle is updated
# (new rooms analyzed, measured averages replacing assumed ranges, etc.)
# rather than run once and discarded.

import json
import sys

REFERENCE_ROOM_LABEL = "Lavatory"


def pick_seconds(room):
    """Selects the single visit-duration figure for a room, based on its
    recommended strategy. Returns None if the room has no numeric range at
    all (e.g. Skinnydip, which isn't a constructed room)."""
    duration_range = room.get("totalVisitSecondsAssumedRange")
    if duration_range is None:
        return None

    strategy = room.get("recommendedStrategy")
    minimum_seconds = duration_range["min"]
    maximum_seconds = duration_range["max"]

    if strategy == "minimum":
        return minimum_seconds
    elif strategy == "maximum":
        return maximum_seconds
    elif strategy == "measured_average":
        return (minimum_seconds + maximum_seconds) / 2.0
    else:
        # exclude_or_default, or any future strategy we haven't handled yet.
        return None


def build_output(source_bundle):
    rooms_by_label = {room["roomLabel"]: room for room in source_bundle["rooms"]}

    if REFERENCE_ROOM_LABEL not in rooms_by_label:
        raise ValueError(f"Reference room '{REFERENCE_ROOM_LABEL}' not found in source bundle.")

    reference_seconds = pick_seconds(rooms_by_label[REFERENCE_ROOM_LABEL])
    if reference_seconds is None:
        raise ValueError(f"Reference room '{REFERENCE_ROOM_LABEL}' has no usable duration figure.")

    output_rooms = {}
    excluded_rooms = []

    for room in source_bundle["rooms"]:
        chosen_seconds = pick_seconds(room)
        if chosen_seconds is None:
            excluded_rooms.append({
                "roomLabel": room["roomLabel"],
                "reason": room.get("strategyReason", "no numeric duration available"),
            })
            continue

        output_rooms[room["needKey"]] = {
            "roomLabel": room["roomLabel"],
            "strategyUsed": room["recommendedStrategy"],
            "visitSeconds": round(chosen_seconds, 3),
            "durationRatioToReference": round(chosen_seconds / reference_seconds, 4),
        }

    return {
        "note": "Generated by process_visit_durations.py. Keys are the source bundle's needKey values, matching each room's actual NEED.key in-game (e.g. CONSTIPATION for Lavatory, _SHRINE for Shrine) - not blueprintClass or RoomBlueprintImp.key.",
        "referenceRoom": REFERENCE_ROOM_LABEL,
        "referenceRoomSeconds": round(reference_seconds, 3),
        "rooms": output_rooms,
        "excludedRooms": excluded_rooms,
        "roomsNotYetAnalyzed": source_bundle.get("roomsNotYetAnalyzed", []),
        "inheritedCaveats": source_bundle.get("globalCaveats", []),
    }


def main():
    input_path = sys.argv[1] if len(sys.argv) > 1 else "thal-visit-duration-source-data.json"
    output_path = sys.argv[2] if len(sys.argv) > 2 else "thal-visit-duration-final.json"

    with open(input_path, "r") as input_file:
        source_bundle = json.load(input_file)

    output_data = build_output(source_bundle)

    with open(output_path, "w") as output_file:
        json.dump(output_data, output_file, indent=2)
        output_file.write("\n")

    print(f"Wrote {len(output_data['rooms'])} room(s) to {output_path}")
    print(f"Reference room: {output_data['referenceRoom']} "
          f"({output_data['referenceRoomSeconds']}s)")
    for need_key, room_data in output_data["rooms"].items():
        print(f"  {need_key}: {room_data['visitSeconds']}s "
              f"(x{room_data['durationRatioToReference']}, "
              f"{room_data['strategyUsed']})")
    if output_data["excludedRooms"]:
        print("Excluded (no numeric strategy applied):")
        for excluded in output_data["excludedRooms"]:
            print(f"  {excluded['roomLabel']}: {excluded['reason']}")


if __name__ == "__main__":
    main()
