// ThalServiceVisitDurations.java
// Document Version 2.0.0
// Creation date: 2026/07/13
// Creator: Thalassicus

package thalassicus.util;

import game.time.TIME;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//
// ============================================================================
// THAL SERVICE VISIT DURATIONS
// ============================================================================
// Supplies a per-BLUEPRINT replacement for TIME.servicePerDay(), the flat
// constant (always 4) that RoomService.totalMultiplier() applies uniformly
// to every ordinary-NEED service regardless of how long a real visit
// actually takes. Real per-visit occupancy time varies by room type
// (confirmed directly in each room's AI plan class, e.g. M_PlanWell vs
// M_PlanLavatory vs S_PlanTemple), a variance TIME.servicePerDay() has no
// way to represent.
//
// Looked up by real in-game BLUEPRINT KEY (RoomBlueprintImp.key, e.g.
// "LAVATORY_NORMAL", "_HEARTH", "TEMPLE_ATHURI"), not by NEED key. This
// supersedes an earlier version of this class that looked up by NEED,
// which broke down once Temple confirmed that multiple blueprints (one
// per religion) can share a single NEED with genuinely distinct data - a
// NEED can no longer identify a specific blueprint's duration, only a
// blueprint key can. Callers must supply the specific room's own blueprint
// key (typically roomService.room().key), not its NEED.
//
// Rather than guess at absolute visit durations from RND.rInt() chains in
// source, the real figures are measured and bundled as a data file
// (thal-visit-duration-final.json, generated by a Python script from a
// hand-assembled research bundle; see the mod's project notes) deployed
// alongside this mod, not tied into Jake's own data-loading system.
// Lavatory is the reference room, since its capacity estimate was the first
// one validated against real gameplay: servicePerDay() reduces to exactly
// TIME.servicePerDay() for Lavatory itself, and only diverges for a
// blueprint where a real difference was measured (or deliberately chosen;
// see the Hearth/Temple safety-asymmetry notes in the data file itself).
//
// A longer real visit duration than the reference room produces a LARGER
// corrected value here, which in turn produces a SMALLER final capacity
// estimate in correctedCapacityMultipliers() - this constant sits in the
// numerator of an expression that is itself inverted, so it moves the
// opposite way "more services per day" might suggest at a glance.
//
// This is a small, purpose-built parser tailored to the exact flat structure
// this mod's own script produces, not a general JSON parser. It assumes:
// - a top-level "referenceRoomSeconds" numeric field,
// - every blueprint-keyed room entry is a flat object (no nested braces)
//   containing a "visitSeconds" numeric field (a value of -1 is a
//   deliberate sentinel meaning "a real blueprint key exists, but no
//   measured data does yet" - this is handled for free by the same
//   fallback logic below that treats any non-positive value as "no usable
//   entry", no separate check needed),
// - blueprint keys are all-uppercase, optionally with a leading underscore
//   (matching every confirmed blueprint key seen in the game's own data so
//   far, e.g. LAVATORY_NORMAL, _HEARTH, TEMPLE_ATHURI), which lets one
//   regex distinguish real room entries from the file's other structural
//   keys ("rooms", "note", etc.) without needing to isolate the "rooms"
//   section explicitly.
// If the data file is missing, unreadable, or contains no entry (or a -1
// sentinel entry) for a given blueprint key, this silently falls back to
// TIME.servicePerDay() - the vanilla behavior - rather than risk a wrong
// number from a partially-parsed file or an unmeasured room.
// ============================================================================
//

public class ThalServiceVisitDurations {

  private static final ThalsLogger log = new ThalsLogger(
      ThalsLogger.INFO,
      System.getenv("APPDATA") + "\\songsofsyx\\logs\\ThalServiceEstimateFix.log"
  );

  private static final String DATA_FILE_PATH =
      System.getenv("APPDATA") + "\\songsofsyx\\mods\\Service Estimate Fix\\V71\\thal-visit-duration-final.json";

  private static final Pattern REFERENCE_SECONDS_PATTERN =
      Pattern.compile("\"referenceRoomSeconds\"\\s*:\\s*([0-9.eE+-]+)");

  private static final Pattern ROOM_ENTRY_PATTERN =
      Pattern.compile("\"([A-Z_][A-Z0-9_]*)\"\\s*:\\s*\\{[^}]*\"visitSeconds\"\\s*:\\s*([0-9.eE+-]+)[^}]*\\}");

  private static Map<String, Double> visitSecondsByBlueprintKey;
  private static double referenceRoomSeconds;
  private static boolean dataFileLoaded;

  public static double servicePerDay(String blueprintKey) {
    ensureLoaded();

    Double measuredVisitSeconds = visitSecondsByBlueprintKey.get(blueprintKey);
    if (measuredVisitSeconds == null || measuredVisitSeconds <= 0.0 || referenceRoomSeconds <= 0.0) {
      log.trace("servicePerDay(%s): no usable entry, falling back to TIME.servicePerDay() = %d",
          blueprintKey, TIME.servicePerDay());
      return TIME.servicePerDay();
    }

    double correctedValue = TIME.servicePerDay() * measuredVisitSeconds / referenceRoomSeconds;
    log.trace("servicePerDay(%s): measured=%.3fs, reference=%.3fs -> corrected=%.3f (vanilla=%d)",
        blueprintKey, measuredVisitSeconds, referenceRoomSeconds, correctedValue, TIME.servicePerDay());
    return correctedValue;
  }

  public static boolean dataFileLoaded() {
    ensureLoaded();
    return dataFileLoaded;
  }

  // Returns the raw measured average visit-duration in seconds for the
  // given blueprint key, or -1.0 if no measured entry exists for it
  // (Skinnydip has no blueprint key at all so can never appear here;
  // Hospital, Canteen, Eatery, and Court have real blueprint keys but no
  // measured data yet, stored as an explicit -1 sentinel in the data file
  // itself - see thal-visit-duration-final.json's own note field).
  //
  // Deliberately does NOT fall back to TIME.servicePerDay() the way
  // servicePerDay(String) does above: that fallback produces a corrected
  // capacity-formula RATE (visits-per-day-equivalent), not a real
  // duration-in-seconds figure, and calibration work built on Little's Law
  // needs the latter specifically - substituting the former here would be
  // silently wrong, not just imprecise. Callers should treat a -1.0 return
  // as "no real data, skip calibration for this blueprint" rather than
  // substitute a guessed duration.
  public static double visitSeconds(String blueprintKey) {
    ensureLoaded();
    Double measuredVisitSeconds = visitSecondsByBlueprintKey.get(blueprintKey);
    return measuredVisitSeconds == null ? -1.0 : measuredVisitSeconds;
  }

  private static void ensureLoaded() {
    if (visitSecondsByBlueprintKey != null) {
      return;
    }

    visitSecondsByBlueprintKey = new HashMap<>();
    referenceRoomSeconds = 0.0;
    dataFileLoaded = false;

    String fileContents;
    try {
      fileContents = Files.readString(Path.of(DATA_FILE_PATH));
    } catch (IOException readFailure) {
      log.warn("Could not read visit-duration data file at %s (%s); falling back to TIME.servicePerDay() for every service.",
          DATA_FILE_PATH, readFailure.getMessage());
      return;
    }

    try {
      Matcher referenceMatcher = REFERENCE_SECONDS_PATTERN.matcher(fileContents);
      if (referenceMatcher.find()) {
        referenceRoomSeconds = Double.parseDouble(referenceMatcher.group(1));
      }

      Matcher roomMatcher = ROOM_ENTRY_PATTERN.matcher(fileContents);
      while (roomMatcher.find()) {
        String blueprintKey = roomMatcher.group(1);
        double visitSeconds = Double.parseDouble(roomMatcher.group(2));
        visitSecondsByBlueprintKey.put(blueprintKey, visitSeconds);
      }
    } catch (NumberFormatException parseFailure) {
      log.warn("Visit-duration data file at %s contained an unparseable number (%s); falling back to TIME.servicePerDay() for every service.",
          DATA_FILE_PATH, parseFailure.getMessage());
      visitSecondsByBlueprintKey.clear();
      referenceRoomSeconds = 0.0;
      return;
    }

    dataFileLoaded = referenceRoomSeconds > 0.0 && !visitSecondsByBlueprintKey.isEmpty();
    if (dataFileLoaded) {
      log.info("Loaded %d visit-duration entries from %s; reference room is %.3f seconds.",
          visitSecondsByBlueprintKey.size(), DATA_FILE_PATH, referenceRoomSeconds);
    } else {
      log.warn("Visit-duration data file at %s parsed without error but contained no usable entries (referenceRoomSeconds=%.3f, rooms=%d); falling back to TIME.servicePerDay() for every service.",
          DATA_FILE_PATH, referenceRoomSeconds, visitSecondsByBlueprintKey.size());
    }
  }
}
