// ThalServiceVisitDurations.java
// Document Version 1.1.0
// Creation date: 2026/07/13
// Creator: Thalassicus

package thalassicus;

import game.time.TIME;
import init.type.NEED;
import thalassicus.util.ThalsLogger;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.HashMap;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

//
// ============================================================================
// THAL SERVICE VISIT DURATIONS
// ============================================================================
// Supplies a per-NEED replacement for TIME.servicePerDay(), the flat constant
// (always 4) that RoomService.totalMultiplier() applies uniformly to every
// ordinary-NEED service regardless of how long a real visit actually takes.
// Real per-visit occupancy time varies by room type (confirmed directly in
// each room's AI plan class, e.g. M_PlanWell vs M_PlanLavatory vs
// S_PlanTemple), a variance TIME.servicePerDay() has no way to represent.
//
// Rather than guess at absolute visit durations from RND.rInt() chains in
// source, the real figures are measured and bundled as a data file
// (thal-visit-duration-final.json, generated by a Python script from a
// hand-assembled research bundle; see the mod's project notes) deployed
// alongside this mod, not tied into Jake's own data-loading system.
// Lavatory is the reference room, since its capacity estimate was the first
// one validated against real gameplay: servicePerDay() reduces to exactly
// TIME.servicePerDay() for Lavatory itself, and only diverges for a NEED
// where a real difference was measured (or deliberately chosen; see the
// Hearth/Temple safety-asymmetry notes in the data file itself).
//
// A longer real visit duration than the reference room produces a LARGER
// corrected value here, which in turn produces a SMALLER final capacity
// estimate in correctedMultiplier() - this constant sits in the numerator
// of an expression that is itself inverted, so it moves the opposite way
// "more services per day" might suggest at a glance.
//
// This is a small, purpose-built parser tailored to the exact flat structure
// this mod's own script produces, not a general JSON parser. It assumes:
// - a top-level "referenceRoomSeconds" numeric field,
// - every NEED-keyed room entry is a flat object (no nested braces)
//   containing a "visitSeconds" numeric field,
// - NEED keys are all-uppercase, optionally with a leading underscore
//   (matching every NEED key seen in the game's own data so far, including
//   the underscore-prefixed _SHRINE and _TEMPLE), which lets one regex
//   distinguish real room entries from the file's other structural keys
//   ("rooms", "note", etc.) without needing to isolate the "rooms" section
//   explicitly.
// If the data file is missing, unreadable, or contains no entry for a given
// NEED, this silently falls back to TIME.servicePerDay() - the vanilla
// behavior - rather than risk a wrong number from a partially-parsed file.
// ============================================================================
//

public class ThalServiceVisitDurations {

  private static final ThalsLogger log = new ThalsLogger(
      ThalsLogger.INFO,
      System.getenv("APPDATA") + "\\songsofsyx\\logs\\ThalServiceEstimateFix.log"
  );

  private static final String DATA_FILE_PATH =
      System.getenv("APPDATA") + "\\songsofsyx\\mods\\Service Estimate Fix\\V71\\thal-visit-duration-final.json";

  private static final Pattern REFERENCE_SECONDS_PATTERN =
      Pattern.compile("\"referenceRoomSeconds\"\\s*:\\s*([0-9.eE+-]+)");

  private static final Pattern ROOM_ENTRY_PATTERN =
      Pattern.compile("\"([A-Z_][A-Z0-9_]*)\"\\s*:\\s*\\{[^}]*\"visitSeconds\"\\s*:\\s*([0-9.eE+-]+)[^}]*\\}");

  private static Map<String, Double> visitSecondsByNeedKey;
  private static double referenceRoomSeconds;
  private static boolean dataFileLoaded;

  public static double servicePerDay(NEED serviceNeed) {
    ensureLoaded();

    Double measuredVisitSeconds = visitSecondsByNeedKey.get(serviceNeed.key);
    if (measuredVisitSeconds == null || measuredVisitSeconds <= 0.0 || referenceRoomSeconds <= 0.0) {
      log.trace("servicePerDay(%s): no usable entry, falling back to TIME.servicePerDay() = %d",
          serviceNeed.key, TIME.servicePerDay());
      return TIME.servicePerDay();
    }

    double correctedValue = TIME.servicePerDay() * measuredVisitSeconds / referenceRoomSeconds;
    log.trace("servicePerDay(%s): measured=%.3fs, reference=%.3fs -> corrected=%.3f (vanilla=%d)",
        serviceNeed.key, measuredVisitSeconds, referenceRoomSeconds, correctedValue, TIME.servicePerDay());
    return correctedValue;
  }

  public static boolean dataFileLoaded() {
    ensureLoaded();
    return dataFileLoaded;
  }

  private static void ensureLoaded() {
    if (visitSecondsByNeedKey != null) {
      return;
    }

    visitSecondsByNeedKey = new HashMap<>();
    referenceRoomSeconds = 0.0;
    dataFileLoaded = false;

    String fileContents;
    try {
      fileContents = Files.readString(Path.of(DATA_FILE_PATH));
    } catch (IOException readFailure) {
      log.warn("Could not read visit-duration data file at %s (%s); falling back to TIME.servicePerDay() for every service.",
          DATA_FILE_PATH, readFailure.getMessage());
      return;
    }

    try {
      Matcher referenceMatcher = REFERENCE_SECONDS_PATTERN.matcher(fileContents);
      if (referenceMatcher.find()) {
        referenceRoomSeconds = Double.parseDouble(referenceMatcher.group(1));
      }

      Matcher roomMatcher = ROOM_ENTRY_PATTERN.matcher(fileContents);
      while (roomMatcher.find()) {
        String needKey = roomMatcher.group(1);
        double visitSeconds = Double.parseDouble(roomMatcher.group(2));
        visitSecondsByNeedKey.put(needKey, visitSeconds);
      }
    } catch (NumberFormatException parseFailure) {
      log.warn("Visit-duration data file at %s contained an unparseable number (%s); falling back to TIME.servicePerDay() for every service.",
          DATA_FILE_PATH, parseFailure.getMessage());
      visitSecondsByNeedKey.clear();
      referenceRoomSeconds = 0.0;
      return;
    }

    dataFileLoaded = referenceRoomSeconds > 0.0 && !visitSecondsByNeedKey.isEmpty();
    if (dataFileLoaded) {
      log.info("Loaded %d visit-duration entries from %s; reference room is %.3f seconds.",
          visitSecondsByNeedKey.size(), DATA_FILE_PATH, referenceRoomSeconds);
    } else {
      log.warn("Visit-duration data file at %s parsed without error but contained no usable entries (referenceRoomSeconds=%.3f, rooms=%d); falling back to TIME.servicePerDay() for every service.",
          DATA_FILE_PATH, referenceRoomSeconds, visitSecondsByNeedKey.size());
    }
  }
}
